### PR TITLE
Migrate to Bootstrap 3 - fixes #11

### LINKED ISSUE #11: Migrate to twitter bootstrap 3.0

### PR DESCRIPTION
**Pull request by daniellee**
This was not just a simple upgrade from version 2 to 3. I have preserved the look from Bootstrap 2. For some elements like the search field, I had to copy the css from Bootstrap 2 into the Asimov less files.

Some mixins have disappeared and with them some background gradients. I'm going to test this on our test server at Tradera before merging this in. I will do some more clean up later and remove unused css and images.

### CODE REVIEW

**Comment by bergquist** [comment]
Whats the status on this PR?

**Comment by daniellee** [comment]
I would like to test it in our test environment first before merging it in. Will do today.

**Comment by kiquenet** [comment]
How build best test environment for testing asimov?

**Comment by daniellee** [comment]
@kiquenet There are two ways to test locally. 

1. Set enable-demo to true in the config file and the Nodefront will use dummy data. This is fine for CSS and JS changes.
2. Run an agent locally. Set the config to point to localhost:3333 (your local nodefront).

However, in this case I tested on the live Asimov server that we use for deploying to our test environment. It has 9 agents (our 9 testservers) and is used every day by our developers. This is not so easy for other people to replicate.

**Comment by daniellee** [comment]
@bergquist  Found two small css glitches that I want to fix before merging this in. The list of versions to deploy doesn't look right. And some of the buttons are too narrow.

**Comment by daniellee** [comment]
Hmm, thinking about not merging this and just staying on Bootstrap 2.

**Pull request closed without merging**
